package ru.xaptenodytes.activizm.model;

// Generated 18.05.2015 14:47:17 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Activists generated by hbm2java
 */
@Entity
@Table(name = "activists", catalog = "activizm", uniqueConstraints = {
		@UniqueConstraint(columnNames = "cityId"),
		@UniqueConstraint(columnNames = "coordinatorId") })
public class Activists implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8839335027019665978L;
	private Integer activistId;
	private Events events;
	private Phones phones;
	private ScheduleWithDate scheduleWithDate;
	private ScheduleWithWeekdays scheduleWithWeekdays;
	private Integer vkId;
	private Integer fbId;
	private String email;
	private String passwdHash;
	private String surname;
	private String name1;
	private String name2;
	private Date registrDate;
	private Date activateDate;
	private Date desactivateDate;
	private int coordinatorId;
	private Boolean status;
	private Integer cityId;
	private Integer districtId;
	private Coordinators coordinators;
	private Cities cities;

	public Activists() {
	}

	public Activists(Events events, Phones phones,
			ScheduleWithDate scheduleWithDate,
			ScheduleWithWeekdays scheduleWithWeekdays, String passwdHash,
			String surname, String name1, Date registrDate, int coordinatorId) {
		this.events = events;
		this.phones = phones;
		this.scheduleWithDate = scheduleWithDate;
		this.scheduleWithWeekdays = scheduleWithWeekdays;
		this.passwdHash = passwdHash;
		this.surname = surname;
		this.name1 = name1;
		this.registrDate = registrDate;
		this.coordinatorId = coordinatorId;
	}

	public Activists(Events events, Phones phones,
			ScheduleWithDate scheduleWithDate,
			ScheduleWithWeekdays scheduleWithWeekdays, Integer vkId,
			Integer fbId, String email, String passwdHash, String surname,
			String name1, String name2, Date registrDate, Date activateDate,
			Date desactivateDate, int coordinatorId, Boolean status,
			Integer cityId, Integer districtId, Coordinators coordinators,
			Cities cities) {
		this.events = events;
		this.phones = phones;
		this.scheduleWithDate = scheduleWithDate;
		this.scheduleWithWeekdays = scheduleWithWeekdays;
		this.vkId = vkId;
		this.fbId = fbId;
		this.email = email;
		this.passwdHash = passwdHash;
		this.surname = surname;
		this.name1 = name1;
		this.name2 = name2;
		this.registrDate = registrDate;
		this.activateDate = activateDate;
		this.desactivateDate = desactivateDate;
		this.coordinatorId = coordinatorId;
		this.status = status;
		this.cityId = cityId;
		this.districtId = districtId;
		this.coordinators = coordinators;
		this.cities = cities;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "events"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "activistId", unique = true, nullable = false)
	public Integer getActivistId() {
		return this.activistId;
	}

	public void setActivistId(Integer activistId) {
		this.activistId = activistId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Events getEvents() {
		return this.events;
	}

	public void setEvents(Events events) {
		this.events = events;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Phones getPhones() {
		return this.phones;
	}

	public void setPhones(Phones phones) {
		this.phones = phones;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public ScheduleWithDate getSchedulewithdate() {
		return this.scheduleWithDate;
	}

	public void setSchedulewithdate(ScheduleWithDate scheduleWithDate) {
		this.scheduleWithDate = scheduleWithDate;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public ScheduleWithWeekdays getSchedulewithweekdays() {
		return this.scheduleWithWeekdays;
	}

	public void setSchedulewithweekdays(
			ScheduleWithWeekdays scheduleWithWeekdays) {
		this.scheduleWithWeekdays = scheduleWithWeekdays;
	}

	@Column(name = "vkID")
	public Integer getVkId() {
		return this.vkId;
	}

	public void setVkId(Integer vkId) {
		this.vkId = vkId;
	}

	@Column(name = "fbId")
	public Integer getFbId() {
		return this.fbId;
	}

	public void setFbId(Integer fbId) {
		this.fbId = fbId;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "passwdHash", nullable = false, length = 100)
	public String getPasswdHash() {
		return this.passwdHash;
	}

	public void setPasswdHash(String passwdHash) {
		this.passwdHash = passwdHash;
	}

	@Column(name = "surname", nullable = false, length = 50)
	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	@Column(name = "name1", nullable = false, length = 50)
	public String getName1() {
		return this.name1;
	}

	public void setName1(String name1) {
		this.name1 = name1;
	}

	@Column(name = "name2", length = 50)
	public String getName2() {
		return this.name2;
	}

	public void setName2(String name2) {
		this.name2 = name2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "registrDate", nullable = false, length = 19)
	public Date getRegistrDate() {
		return this.registrDate;
	}

	public void setRegistrDate(Date registrDate) {
		this.registrDate = registrDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "activateDate", length = 19)
	public Date getActivateDate() {
		return this.activateDate;
	}

	public void setActivateDate(Date activateDate) {
		this.activateDate = activateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "desactivateDate", length = 19)
	public Date getDesactivateDate() {
		return this.desactivateDate;
	}

	public void setDesactivateDate(Date desactivateDate) {
		this.desactivateDate = desactivateDate;
	}

	@Column(name = "coordinatorId", unique = true, nullable = false)
	public int getCoordinatorId() {
		return this.coordinatorId;
	}

	public void setCoordinatorId(int coordinatorId) {
		this.coordinatorId = coordinatorId;
	}

	@Column(name = "STATUS")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "cityId", unique = true)
	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	@Column(name = "districtId")
	public Integer getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(Integer districtId) {
		this.districtId = districtId;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "activists")
	public Coordinators getCoordinators() {
		return this.coordinators;
	}

	public void setCoordinators(Coordinators coordinators) {
		this.coordinators = coordinators;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "activists")
	public Cities getCities() {
		return this.cities;
	}

	public void setCities(Cities cities) {
		this.cities = cities;
	}

}
