package ru.xaptenodytes.activizm.model;

// Generated 01.06.2015 21:49:07 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Areaofresponsibility generated by hbm2java
 */
@Entity
@Table(name = "areaofresponsibility", catalog = "activizm", uniqueConstraints = @UniqueConstraint(columnNames = "userroleId"))
public class Areaofresponsibility implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2106403529309809595L;
	private Integer areaId;
	private Integer userroleId;
	private Double mapPointX;
	private Double mapPointY;
	private Double radius;
	private Userrole Userrole;

	public Areaofresponsibility() {
	}

	public Areaofresponsibility(Integer userroleId, Double mapPointX,
			Double mapPointY, Double radius, Userrole Userrole) {
		this.userroleId = userroleId;
		this.mapPointX = mapPointX;
		this.mapPointY = mapPointY;
		this.radius = radius;
		this.Userrole = Userrole;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "areaId", unique = true, nullable = false)
	public Integer getAreaId() {
		return this.areaId;
	}

	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

	@Column(name = "userroleId", unique = true)
	public Integer getUserroleId() {
		return this.userroleId;
	}

	public void setUserroleId(Integer userroleId) {
		this.userroleId = userroleId;
	}

	@Column(name = "mapPointX", precision = 22, scale = 0)
	public Double getMapPointX() {
		return this.mapPointX;
	}

	public void setMapPointX(Double mapPointX) {
		this.mapPointX = mapPointX;
	}

	@Column(name = "mapPointY", precision = 22, scale = 0)
	public Double getMapPointY() {
		return this.mapPointY;
	}

	public void setMapPointY(Double mapPointY) {
		this.mapPointY = mapPointY;
	}

	@Column(name = "radius", precision = 22, scale = 0)
	public Double getRadius() {
		return this.radius;
	}

	public void setRadius(Double radius) {
		this.radius = radius;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "areaofresponsibility")
	public Userrole getUserrole() {
		return this.Userrole;
	}

	public void setUserrole(Userrole Userrole) {
		this.Userrole = Userrole;
	}

}
