package ru.xaptenodytes.activizm.model;

// Generated 24.05.2015 22:32:50 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Cities generated by hbm2java
 */
@Entity
@Table(name = "cities", catalog = "activizm")
public class Cities implements java.io.Serializable {

	private Integer cityId;
	private Events events;
	private Subcommunities subcommunities;
	private Users users;
	private String cityName;

	public Cities() {
	}

	public Cities(Events events, Subcommunities subcommunities, Users users) {
		this.events = events;
		this.subcommunities = subcommunities;
		this.users = users;
	}

	public Cities(Events events, Subcommunities subcommunities, Users users,
			String cityName) {
		this.events = events;
		this.subcommunities = subcommunities;
		this.users = users;
		this.cityName = cityName;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "events"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "CityId", unique = true, nullable = false)
	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Events getEvents() {
		return this.events;
	}

	public void setEvents(Events events) {
		this.events = events;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Subcommunities getSubcommunities() {
		return this.subcommunities;
	}

	public void setSubcommunities(Subcommunities subcommunities) {
		this.subcommunities = subcommunities;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "CityName", length = 200)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

}
