package ru.xaptenodytes.activizm.model;

// Generated 18.05.2015 14:47:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Cities generated by hbm2java
 */
@Entity
@Table(name = "cities", catalog = "activizm")
public class Cities implements java.io.Serializable {

	private Integer cityId;
	private Activists activists;
	private Coordinators coordinators;
	private Events events;
	private Subcommunities subcommunities;
	private String cityName;

	public Cities() {
	}

	public Cities(Activists activists, Coordinators coordinators,
			Events events, Subcommunities subcommunities) {
		this.activists = activists;
		this.coordinators = coordinators;
		this.events = events;
		this.subcommunities = subcommunities;
	}

	public Cities(Activists activists, Coordinators coordinators,
			Events events, Subcommunities subcommunities, String cityName) {
		this.activists = activists;
		this.coordinators = coordinators;
		this.events = events;
		this.subcommunities = subcommunities;
		this.cityName = cityName;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "activists"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "CityId", unique = true, nullable = false)
	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Activists getActivists() {
		return this.activists;
	}

	public void setActivists(Activists activists) {
		this.activists = activists;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Coordinators getCoordinators() {
		return this.coordinators;
	}

	public void setCoordinators(Coordinators coordinators) {
		this.coordinators = coordinators;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Events getEvents() {
		return this.events;
	}

	public void setEvents(Events events) {
		this.events = events;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Subcommunities getSubcommunities() {
		return this.subcommunities;
	}

	public void setSubcommunities(Subcommunities subcommunities) {
		this.subcommunities = subcommunities;
	}

	@Column(name = "CityName", length = 200)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

}
