package ru.xaptenodytes.activizm.model;

// Generated 19.05.2015 16:37:34 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Cities generated by hbm2java
 */
@Entity
@Table(name = "cities", catalog = "activizm")
public class City implements java.io.Serializable {

	private Integer cityId;
	private Activist activist;
	private Coordinator coordinator;
	private Event event;
	private Subcommunity subcommunity;
	private String cityName;

	public City() {
	}

	public City(Activist activist, Coordinator coordinator,
			Event event, Subcommunity subcommunity) {
		this.activist = activist;
		this.coordinator = coordinator;
		this.event = event;
		this.subcommunity = subcommunity;
	}

	public City(Activist activist, Coordinator coordinator,
			Event event, Subcommunity subcommunity, String cityName) {
		this.activist = activist;
		this.coordinator = coordinator;
		this.event = event;
		this.subcommunity = subcommunity;
		this.cityName = cityName;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "activists"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "CityId", unique = true, nullable = false)
	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Activist getActivists() {
		return this.activist;
	}

	public void setActivists(Activist activist) {
		this.activist = activist;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Coordinator getCoordinators() {
		return this.coordinator;
	}

	public void setCoordinators(Coordinator coordinator) {
		this.coordinator = coordinator;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Event getEvents() {
		return this.event;
	}

	public void setEvents(Event event) {
		this.event = event;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Subcommunity getSubcommunities() {
		return this.subcommunity;
	}

	public void setSubcommunities(Subcommunity subcommunity) {
		this.subcommunity = subcommunity;
	}

	@Column(name = "CityName", length = 200)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

}
