package ru.xaptenodytes.activizm.model;

// Generated 24.05.2015 22:32:50 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Organisationeventtype generated by hbm2java
 */
@Entity
@Table(name = "organisationeventtype", catalog = "activizm", uniqueConstraints = @UniqueConstraint(columnNames = "EventTypeId"))
public class Organisationeventtype implements java.io.Serializable {

	private Integer connectionId;
	private Community community;
	private int eventTypeId;
	private Eventtype eventtype;

	public Organisationeventtype() {
	}

	public Organisationeventtype(Community community, int eventTypeId) {
		this.community = community;
		this.eventTypeId = eventTypeId;
	}

	public Organisationeventtype(Community community, int eventTypeId,
			Eventtype eventtype) {
		this.community = community;
		this.eventTypeId = eventTypeId;
		this.eventtype = eventtype;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "connectionId", unique = true, nullable = false)
	public Integer getConnectionId() {
		return this.connectionId;
	}

	public void setConnectionId(Integer connectionId) {
		this.connectionId = connectionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ComunityId", nullable = false)
	public Community getCommunities() {
		return this.community;
	}

	public void setCommunities(Community community) {
		this.community = community;
	}

	@Column(name = "EventTypeId", unique = true, nullable = false)
	public int getEventTypeId() {
		return this.eventTypeId;
	}

	public void setEventTypeId(int eventTypeId) {
		this.eventTypeId = eventTypeId;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "organisationeventtype")
	public Eventtype getEventtype() {
		return this.eventtype;
	}

	public void setEventtype(Eventtype eventtype) {
		this.eventtype = eventtype;
	}

}
