package ru.xaptenodytes.activizm.model;

// Generated 18.05.2015 14:47:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrganisationeventtypeId generated by hbm2java
 */
@Embeddable
public class OrganisationEventTypeId implements java.io.Serializable {

	private int comunityId;
	private int eventTypeId;

	public OrganisationEventTypeId() {
	}

	public OrganisationEventTypeId(int comunityId, int eventTypeId) {
		this.comunityId = comunityId;
		this.eventTypeId = eventTypeId;
	}

	@Column(name = "ComunityId", nullable = false)
	public int getComunityId() {
		return this.comunityId;
	}

	public void setComunityId(int comunityId) {
		this.comunityId = comunityId;
	}

	@Column(name = "EventTypeId", unique = true, nullable = false)
	public int getEventTypeId() {
		return this.eventTypeId;
	}

	public void setEventTypeId(int eventTypeId) {
		this.eventTypeId = eventTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrganisationEventTypeId))
			return false;
		OrganisationEventTypeId castOther = (OrganisationEventTypeId) other;

		return (this.getComunityId() == castOther.getComunityId())
				&& (this.getEventTypeId() == castOther.getEventTypeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getComunityId();
		result = 37 * result + this.getEventTypeId();
		return result;
	}

}
