package ru.xaptenodytes.activizm.model;

// Generated 18.05.2015 14:47:17 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Organisationeventtype generated by hbm2java
 */
@Entity
@Table(name = "organisationeventtype", catalog = "activizm", uniqueConstraints = @UniqueConstraint(columnNames = "EventTypeId"))
public class OrganisationEventType implements java.io.Serializable {

	private OrganisationEventTypeId id;
	private Communities communities;
	private EventType eventType;

	public OrganisationEventType() {
	}

	public OrganisationEventType(OrganisationEventTypeId id,
			Communities communities) {
		this.id = id;
		this.communities = communities;
	}

	public OrganisationEventType(OrganisationEventTypeId id,
			Communities communities, EventType eventType) {
		this.id = id;
		this.communities = communities;
		this.eventType = eventType;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "comunityId", column = @Column(name = "ComunityId", nullable = false)),
			@AttributeOverride(name = "eventTypeId", column = @Column(name = "EventTypeId", unique = true, nullable = false)) })
	public OrganisationEventTypeId getId() {
		return this.id;
	}

	public void setId(OrganisationEventTypeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ComunityId", nullable = false, insertable = false, updatable = false)
	public Communities getCommunities() {
		return this.communities;
	}

	public void setCommunities(Communities communities) {
		this.communities = communities;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "organisationeventtype")
	public EventType getEventtype() {
		return this.eventType;
	}

	public void setEventtype(EventType eventType) {
		this.eventType = eventType;
	}

}
