package ru.xaptenodytes.activizm.model;

// Generated 18.05.2015 14:47:17 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Phones generated by hbm2java
 */
@Entity
@Table(name = "phones", catalog = "activizm", uniqueConstraints = @UniqueConstraint(columnNames = "activistId"))
public class Phones implements java.io.Serializable {

	private Integer phoneId;
	private String phoneNumber;
	private int activistId;
	private Activists activists;

	public Phones() {
	}

	public Phones(String phoneNumber, int activistId) {
		this.phoneNumber = phoneNumber;
		this.activistId = activistId;
	}

	public Phones(String phoneNumber, int activistId, Activists activists) {
		this.phoneNumber = phoneNumber;
		this.activistId = activistId;
		this.activists = activists;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "phoneId", unique = true, nullable = false)
	public Integer getPhoneId() {
		return this.phoneId;
	}

	public void setPhoneId(Integer phoneId) {
		this.phoneId = phoneId;
	}

	@Column(name = "phoneNumber", nullable = false, length = 50)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "activistId", unique = true, nullable = false)
	public int getActivistId() {
		return this.activistId;
	}

	public void setActivistId(int activistId) {
		this.activistId = activistId;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "events")
	public Activists getActivists() {
		return this.activists;
	}

	public void setActivists(Activists activists) {
		this.activists = activists;
	}

}
