package ru.xaptenodytes.activizm.model;

// Generated 19.05.2015 16:37:34 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Phones generated by hbm2java
 */
@Entity
@Table(name = "phones", catalog = "activizm", uniqueConstraints = @UniqueConstraint(columnNames = "activistId"))
public class Phone implements java.io.Serializable {

	private Integer phoneId;
	private String phoneNumber;
	private int activistId;
	private Activist activist;

	public Phone() {
	}

	public Phone(String phoneNumber, int activistId) {
		this.phoneNumber = phoneNumber;
		this.activistId = activistId;
	}

	public Phone(String phoneNumber, int activistId, Activist activist) {
		this.phoneNumber = phoneNumber;
		this.activistId = activistId;
		this.activist = activist;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "phoneId", unique = true, nullable = false)
	public Integer getPhoneId() {
		return this.phoneId;
	}

	public void setPhoneId(Integer phoneId) {
		this.phoneId = phoneId;
	}

	@Column(name = "phoneNumber", nullable = false, length = 50)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "activistId", unique = true, nullable = false)
	public int getActivistId() {
		return this.activistId;
	}

	public void setActivistId(int activistId) {
		this.activistId = activistId;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "events")
	public Activist getActivists() {
		return this.activist;
	}

	public void setActivists(Activist activist) {
		this.activist = activist;
	}

}
