package ru.xaptenodytes.activizm.model;

// Generated 19.05.2015 16:37:34 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Requester generated by hbm2java
 */
@Entity
@Table(name = "requester", catalog = "activizm")
public class Requester implements java.io.Serializable {

	private Integer requesterId;
	private Event event;
	private Integer vkId;
	private Integer fbId;
	private String email;
	private String hashPasswd;
	private String phoneNumber;
	private Date registrDate;

	public Requester() {
	}

	public Requester(Event event, String hashPasswd, String phoneNumber,
			Date registrDate) {
		this.event = event;
		this.hashPasswd = hashPasswd;
		this.phoneNumber = phoneNumber;
		this.registrDate = registrDate;
	}

	public Requester(Event event, Integer vkId, Integer fbId, String email,
			String hashPasswd, String phoneNumber, Date registrDate) {
		this.event = event;
		this.vkId = vkId;
		this.fbId = fbId;
		this.email = email;
		this.hashPasswd = hashPasswd;
		this.phoneNumber = phoneNumber;
		this.registrDate = registrDate;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "events"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "requesterId", unique = true, nullable = false)
	public Integer getRequesterId() {
		return this.requesterId;
	}

	public void setRequesterId(Integer requesterId) {
		this.requesterId = requesterId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Event getEvents() {
		return this.event;
	}

	public void setEvents(Event event) {
		this.event = event;
	}

	@Column(name = "vkID")
	public Integer getVkId() {
		return this.vkId;
	}

	public void setVkId(Integer vkId) {
		this.vkId = vkId;
	}

	@Column(name = "fbId")
	public Integer getFbId() {
		return this.fbId;
	}

	public void setFbId(Integer fbId) {
		this.fbId = fbId;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "hashPasswd", nullable = false, length = 100)
	public String getHashPasswd() {
		return this.hashPasswd;
	}

	public void setHashPasswd(String hashPasswd) {
		this.hashPasswd = hashPasswd;
	}

	@Column(name = "phoneNumber", nullable = false, length = 50)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "registrDate", nullable = false, length = 19)
	public Date getRegistrDate() {
		return this.registrDate;
	}

	public void setRegistrDate(Date registrDate) {
		this.registrDate = registrDate;
	}

}
