package ru.xaptenodytes.activizm.model;

// Generated 24.05.2015 22:32:50 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles", catalog = "activizm")
public class Role implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1128045489550244436L;
	private Integer roleId;
	private Userrole userrole;
	private String role;
	private String label;
	
	public Role() {
	}

	public Role(Userrole userrole) {
		this.userrole = userrole;
	}

	public Role(Userrole userrole, String roleName) {
		this.userrole = userrole;
		this.role = roleName;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "userroles"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "roleId", unique = true, nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Userrole getUserroles() {
		return this.userrole;
	}

	public void setUserroles(Userrole userrole) {
		this.userrole = userrole;
	}

	@Column(name = "role", length = 50)
	public String getRole() {
		return this.role;
	}
	
	public void setRole(String role) {
		this.role = role;
	}
	
	@Column(name = "label", length = 50)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}
}
