package ru.xaptenodytes.activizm.model;

// Generated 01.06.2015 21:49:07 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Schedulewithdate generated by hbm2java
 */
@Entity
@Table(name = "schedulewithdate", catalog = "activizm", uniqueConstraints = @UniqueConstraint(columnNames = "userId"))
public class Schedulewithdate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7543178340645501057L;
	private Integer sheldueWithDateId;
	private int userId;
	private Double mapPointX;
	private Double mapPointY;
	private Integer radius;
	private Date beginDate;
	private Date endDate;
	private User users;

	public Schedulewithdate() {
	}

	public Schedulewithdate(int userId) {
		this.userId = userId;
	}

	public Schedulewithdate(int userId, Double mapPointX, Double mapPointY,
			Integer radius, Date beginDate, Date endDate, User users) {
		this.userId = userId;
		this.mapPointX = mapPointX;
		this.mapPointY = mapPointY;
		this.radius = radius;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sheldueWithDateId", unique = true, nullable = false)
	public Integer getSheldueWithDateId() {
		return this.sheldueWithDateId;
	}

	public void setSheldueWithDateId(Integer sheldueWithDateId) {
		this.sheldueWithDateId = sheldueWithDateId;
	}

	@Column(name = "userId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "MapPointX", precision = 22, scale = 0)
	public Double getMapPointX() {
		return this.mapPointX;
	}

	public void setMapPointX(Double mapPointX) {
		this.mapPointX = mapPointX;
	}

	@Column(name = "MapPointY", precision = 22, scale = 0)
	public Double getMapPointY() {
		return this.mapPointY;
	}

	public void setMapPointY(Double mapPointY) {
		this.mapPointY = mapPointY;
	}

	@Column(name = "Radius")
	public Integer getRadius() {
		return this.radius;
	}

	public void setRadius(Integer radius) {
		this.radius = radius;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "beginDate", length = 19)
	public Date getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EndDate", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "phones")
	public User getUsers() {
		return this.users;
	}

	public void setUsers(User users) {
		this.users = users;
	}

}
