package ru.xaptenodytes.activizm.model;

// Generated 18.05.2015 14:47:17 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SchedulewithweekdaysId generated by hbm2java
 */
@Embeddable
public class ScheduleWithWeekdaysId implements java.io.Serializable {

	private int activistId;
	private Double mapPointX;
	private Double mapPointY;
	private Integer radius;
	private Integer weekday;
	private Date beginTime;
	private Date endTime;

	public ScheduleWithWeekdaysId() {
	}

	public ScheduleWithWeekdaysId(int activistId) {
		this.activistId = activistId;
	}

	public ScheduleWithWeekdaysId(int activistId, Double mapPointX,
			Double mapPointY, Integer radius, Integer weekday, Date beginTime,
			Date endTime) {
		this.activistId = activistId;
		this.mapPointX = mapPointX;
		this.mapPointY = mapPointY;
		this.radius = radius;
		this.weekday = weekday;
		this.beginTime = beginTime;
		this.endTime = endTime;
	}

	@Column(name = "ActivistId", unique = true, nullable = false)
	public int getActivistId() {
		return this.activistId;
	}

	public void setActivistId(int activistId) {
		this.activistId = activistId;
	}

	@Column(name = "MapPointX", precision = 22, scale = 0)
	public Double getMapPointX() {
		return this.mapPointX;
	}

	public void setMapPointX(Double mapPointX) {
		this.mapPointX = mapPointX;
	}

	@Column(name = "MapPointY", precision = 22, scale = 0)
	public Double getMapPointY() {
		return this.mapPointY;
	}

	public void setMapPointY(Double mapPointY) {
		this.mapPointY = mapPointY;
	}

	@Column(name = "Radius")
	public Integer getRadius() {
		return this.radius;
	}

	public void setRadius(Integer radius) {
		this.radius = radius;
	}

	@Column(name = "Weekday")
	public Integer getWeekday() {
		return this.weekday;
	}

	public void setWeekday(Integer weekday) {
		this.weekday = weekday;
	}

	@Column(name = "beginTime", length = 19)
	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	@Column(name = "endTime", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ScheduleWithWeekdaysId))
			return false;
		ScheduleWithWeekdaysId castOther = (ScheduleWithWeekdaysId) other;

		return (this.getActivistId() == castOther.getActivistId())
				&& ((this.getMapPointX() == castOther.getMapPointX()) || (this
						.getMapPointX() != null
						&& castOther.getMapPointX() != null && this
						.getMapPointX().equals(castOther.getMapPointX())))
				&& ((this.getMapPointY() == castOther.getMapPointY()) || (this
						.getMapPointY() != null
						&& castOther.getMapPointY() != null && this
						.getMapPointY().equals(castOther.getMapPointY())))
				&& ((this.getRadius() == castOther.getRadius()) || (this
						.getRadius() != null && castOther.getRadius() != null && this
						.getRadius().equals(castOther.getRadius())))
				&& ((this.getWeekday() == castOther.getWeekday()) || (this
						.getWeekday() != null && castOther.getWeekday() != null && this
						.getWeekday().equals(castOther.getWeekday())))
				&& ((this.getBeginTime() == castOther.getBeginTime()) || (this
						.getBeginTime() != null
						&& castOther.getBeginTime() != null && this
						.getBeginTime().equals(castOther.getBeginTime())))
				&& ((this.getEndTime() == castOther.getEndTime()) || (this
						.getEndTime() != null && castOther.getEndTime() != null && this
						.getEndTime().equals(castOther.getEndTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getActivistId();
		result = 37 * result
				+ (getMapPointX() == null ? 0 : this.getMapPointX().hashCode());
		result = 37 * result
				+ (getMapPointY() == null ? 0 : this.getMapPointY().hashCode());
		result = 37 * result
				+ (getRadius() == null ? 0 : this.getRadius().hashCode());
		result = 37 * result
				+ (getWeekday() == null ? 0 : this.getWeekday().hashCode());
		result = 37 * result
				+ (getBeginTime() == null ? 0 : this.getBeginTime().hashCode());
		result = 37 * result
				+ (getEndTime() == null ? 0 : this.getEndTime().hashCode());
		return result;
	}

}
