package ru.xaptenodytes.activizm.model;

// Generated 19.05.2015 16:37:34 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Schedulewithweekdays generated by hbm2java
 */
@Entity
@Table(name = "schedulewithweekdays", catalog = "activizm", uniqueConstraints = @UniqueConstraint(columnNames = "ActivistId"))
public class Schedulewithweekdays implements java.io.Serializable {

	private Integer sheldueWithWeekdaysId;
	private int activistId;
	private Double mapPointX;
	private Double mapPointY;
	private Integer radius;
	private Integer weekday;
	private Date beginTime;
	private Date endTime;
	private Activist activist;

	public Schedulewithweekdays() {
	}

	public Schedulewithweekdays(int activistId) {
		this.activistId = activistId;
	}

	public Schedulewithweekdays(int activistId, Double mapPointX,
			Double mapPointY, Integer radius, Integer weekday, Date beginTime,
			Date endTime, Activist activist) {
		this.activistId = activistId;
		this.mapPointX = mapPointX;
		this.mapPointY = mapPointY;
		this.radius = radius;
		this.weekday = weekday;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.activist = activist;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sheldueWithWeekdaysId", unique = true, nullable = false)
	public Integer getSheldueWithWeekdaysId() {
		return this.sheldueWithWeekdaysId;
	}

	public void setSheldueWithWeekdaysId(Integer sheldueWithWeekdaysId) {
		this.sheldueWithWeekdaysId = sheldueWithWeekdaysId;
	}

	@Column(name = "ActivistId", unique = true, nullable = false)
	public int getActivistId() {
		return this.activistId;
	}

	public void setActivistId(int activistId) {
		this.activistId = activistId;
	}

	@Column(name = "MapPointX", precision = 22, scale = 0)
	public Double getMapPointX() {
		return this.mapPointX;
	}

	public void setMapPointX(Double mapPointX) {
		this.mapPointX = mapPointX;
	}

	@Column(name = "MapPointY", precision = 22, scale = 0)
	public Double getMapPointY() {
		return this.mapPointY;
	}

	public void setMapPointY(Double mapPointY) {
		this.mapPointY = mapPointY;
	}

	@Column(name = "Radius")
	public Integer getRadius() {
		return this.radius;
	}

	public void setRadius(Integer radius) {
		this.radius = radius;
	}

	@Column(name = "Weekday")
	public Integer getWeekday() {
		return this.weekday;
	}

	public void setWeekday(Integer weekday) {
		this.weekday = weekday;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "beginTime", length = 19)
	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "endTime", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "events")
	public Activist getActivists() {
		return this.activist;
	}

	public void setActivists(Activist activist) {
		this.activist = activist;
	}

}
