package ru.xaptenodytes.activizm.model;

// Generated 18.05.2015 14:47:17 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Schedulewithdate generated by hbm2java
 */
@Entity
@Table(name = "schedulewithdate", catalog = "activizm", uniqueConstraints = @UniqueConstraint(columnNames = "ActivistId"))
public class ScheduleWithDate implements java.io.Serializable {

	private ScheduleWithDateId id;
	private Activists activists;

	public ScheduleWithDate() {
	}

	public ScheduleWithDate(ScheduleWithDateId id) {
		this.id = id;
	}

	public ScheduleWithDate(ScheduleWithDateId id, Activists activists) {
		this.id = id;
		this.activists = activists;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "activistId", column = @Column(name = "ActivistId", unique = true, nullable = false)),
			@AttributeOverride(name = "mapPointX", column = @Column(name = "MapPointX", precision = 22, scale = 0)),
			@AttributeOverride(name = "mapPointY", column = @Column(name = "MapPointY", precision = 22, scale = 0)),
			@AttributeOverride(name = "radius", column = @Column(name = "Radius")),
			@AttributeOverride(name = "beginDate", column = @Column(name = "beginDate", length = 19)),
			@AttributeOverride(name = "endDate", column = @Column(name = "EndDate", length = 19)) })
	public ScheduleWithDateId getId() {
		return this.id;
	}

	public void setId(ScheduleWithDateId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "events")
	public Activists getActivists() {
		return this.activists;
	}

	public void setActivists(Activists activists) {
		this.activists = activists;
	}

}
