package ru.xaptenodytes.activizm.model;

// Generated 18.05.2015 14:47:17 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Subcommunities generated by hbm2java
 */
@Entity
@Table(name = "subcommunities", catalog = "activizm", uniqueConstraints = {
		@UniqueConstraint(columnNames = "CityId"),
		@UniqueConstraint(columnNames = "ComunityId") })
public class Subcommunities implements java.io.Serializable {

	private Integer subcomunityId;
	private int comunityId;
	private String subcomunityName;
	private Integer cityId;
	private Set coordinatorses = new HashSet(0);
	private Communities communities;
	private Cities cities;

	public Subcommunities() {
	}

	public Subcommunities(int comunityId, String subcomunityName) {
		this.comunityId = comunityId;
		this.subcomunityName = subcomunityName;
	}

	public Subcommunities(int comunityId, String subcomunityName,
			Integer cityId, Set coordinatorses, Communities communities,
			Cities cities) {
		this.comunityId = comunityId;
		this.subcomunityName = subcomunityName;
		this.cityId = cityId;
		this.coordinatorses = coordinatorses;
		this.communities = communities;
		this.cities = cities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "subcomunityId", unique = true, nullable = false)
	public Integer getSubcomunityId() {
		return this.subcomunityId;
	}

	public void setSubcomunityId(Integer subcomunityId) {
		this.subcomunityId = subcomunityId;
	}

	@Column(name = "ComunityId", unique = true, nullable = false)
	public int getComunityId() {
		return this.comunityId;
	}

	public void setComunityId(int comunityId) {
		this.comunityId = comunityId;
	}

	@Column(name = "SubcomunityName", nullable = false, length = 150)
	public String getSubcomunityName() {
		return this.subcomunityName;
	}

	public void setSubcomunityName(String subcomunityName) {
		this.subcomunityName = subcomunityName;
	}

	@Column(name = "CityId", unique = true)
	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subcommunities")
	public Set getCoordinatorses() {
		return this.coordinatorses;
	}

	public void setCoordinatorses(Set coordinatorses) {
		this.coordinatorses = coordinatorses;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "subcommunities")
	public Communities getCommunities() {
		return this.communities;
	}

	public void setCommunities(Communities communities) {
		this.communities = communities;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "activists")
	public Cities getCities() {
		return this.cities;
	}

	public void setCities(Cities cities) {
		this.cities = cities;
	}

}
