package ru.xaptenodytes.activizm.model;

// Generated 24.05.2015 22:32:50 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Userroles generated by hbm2java
 */
@Entity
@Table(name = "userroles", catalog = "activizm", uniqueConstraints = @UniqueConstraint(columnNames = "roleId"))
public class Userroles implements java.io.Serializable {

	private Integer userroleId;
	private Areaofresponsibility areaofresponsibility;
	private Userroleevents userroleevents;
	private Users users;
	private int roleId;
	private Roles roles;

	public Userroles() {
	}

	public Userroles(Areaofresponsibility areaofresponsibility,
			Userroleevents userroleevents, Users users, int roleId) {
		this.areaofresponsibility = areaofresponsibility;
		this.userroleevents = userroleevents;
		this.users = users;
		this.roleId = roleId;
	}

	public Userroles(Areaofresponsibility areaofresponsibility,
			Userroleevents userroleevents, Users users, int roleId, Roles roles) {
		this.areaofresponsibility = areaofresponsibility;
		this.userroleevents = userroleevents;
		this.users = users;
		this.roleId = roleId;
		this.roles = roles;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "areaofresponsibility"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "userroleId", unique = true, nullable = false)
	public Integer getUserroleId() {
		return this.userroleId;
	}

	public void setUserroleId(Integer userroleId) {
		this.userroleId = userroleId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Areaofresponsibility getAreaofresponsibility() {
		return this.areaofresponsibility;
	}

	public void setAreaofresponsibility(
			Areaofresponsibility areaofresponsibility) {
		this.areaofresponsibility = areaofresponsibility;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Userroleevents getUserroleevents() {
		return this.userroleevents;
	}

	public void setUserroleevents(Userroleevents userroleevents) {
		this.userroleevents = userroleevents;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "roleId", unique = true, nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "userroles")
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

}
