package ru.xaptenodytes.activizm.model;

// Generated 01.06.2015 21:49:07 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usersubcommunity generated by hbm2java
 */
@Entity
@Table(name = "usersubcommunity", catalog = "activizm", uniqueConstraints = @UniqueConstraint(columnNames = "userId"))
public class Usersubcommunity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -757854071660217220L;
	private Integer usersubcommunityId;
	private Subcommunity Subcommunity;
	private int userId;
	private User users;

	public Usersubcommunity() {
	}

	public Usersubcommunity(Subcommunity Subcommunity, int userId) {
		this.Subcommunity = Subcommunity;
		this.userId = userId;
	}

	public Usersubcommunity(Subcommunity Subcommunity, int userId,
			User users) {
		this.Subcommunity = Subcommunity;
		this.userId = userId;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "usersubcommunityId", unique = true, nullable = false)
	public Integer getUsersubcommunityId() {
		return this.usersubcommunityId;
	}

	public void setUsersubcommunityId(Integer usersubcommunityId) {
		this.usersubcommunityId = usersubcommunityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subcommunityId", nullable = false)
	public Subcommunity getSubcommunity() {
		return this.Subcommunity;
	}

	public void setSubcommunity(Subcommunity Subcommunity) {
		this.Subcommunity = Subcommunity;
	}

	@Column(name = "userId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "phones")
	public User getUsers() {
		return this.users;
	}

	public void setUsers(User users) {
		this.users = users;
	}

}
