package ru.xaptenodytes.activizm.model;

// Generated 24.05.2015 22:32:50 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Userroleevents generated by hbm2java
 */
@Entity
@Table(name = "userroleevents", catalog = "activizm", uniqueConstraints = @UniqueConstraint(columnNames = "userroleId"))
public class Userroleevents implements java.io.Serializable {

	private Integer userroleeventId;
	private Events events;
	private int userroleId;
	private Date eventSignDate;
	private Userroles userroles;

	public Userroleevents() {
	}

	public Userroleevents(Events events, int userroleId, Date eventSignDate) {
		this.events = events;
		this.userroleId = userroleId;
		this.eventSignDate = eventSignDate;
	}

	public Userroleevents(Events events, int userroleId, Date eventSignDate,
			Userroles userroles) {
		this.events = events;
		this.userroleId = userroleId;
		this.eventSignDate = eventSignDate;
		this.userroles = userroles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "userroleeventId", unique = true, nullable = false)
	public Integer getUserroleeventId() {
		return this.userroleeventId;
	}

	public void setUserroleeventId(Integer userroleeventId) {
		this.userroleeventId = userroleeventId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eventId", nullable = false)
	public Events getEvents() {
		return this.events;
	}

	public void setEvents(Events events) {
		this.events = events;
	}

	@Column(name = "userroleId", unique = true, nullable = false)
	public int getUserroleId() {
		return this.userroleId;
	}

	public void setUserroleId(int userroleId) {
		this.userroleId = userroleId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "eventSignDate", nullable = false, length = 19)
	public Date getEventSignDate() {
		return this.eventSignDate;
	}

	public void setEventSignDate(Date eventSignDate) {
		this.eventSignDate = eventSignDate;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "areaofresponsibility")
	public Userroles getUserroles() {
		return this.userroles;
	}

	public void setUserroles(Userroles userroles) {
		this.userroles = userroles;
	}

}
